Add Flysystem achievement
eufossa/symfony-hackathon-2019 pull request #18
Opened 2019-04-08 21:50 UTC by tgalopin

2019-04-09 05:51 UTC, OskarStark commented on achievements/flysystem.md
> +features of Flysystem and creating a Symfony Flex recipe.
Missing new line

2019-04-09 05:51 UTC, greg0ire commented on achievements/flysystem.md
> +In January 2018, I stumbled a problem with autowiring: how can one easily and
```suggestion
In January 2018, I stumbled upon a problem with autowiring: how can one easily and 
```

2019-04-09 05:51 UTC, greg0ire commented on achievements/flysystem.md
> +This problem lead to a vast conversation throughout 2018 with Nicolas and
We know who you are talking about, but I'm not sure everyone will :)
```suggestion
This problem lead to a vast conversation throughout 2018 with Nicolas Grekas and 
```

2019-04-09 05:51 UTC, greg0ire commented on achievements/flysystem.md
> +Gregoire Paris to write its documentation
:blush:

2019-04-09 05:51 UTC, greg0ire commented on achievements/flysystem.md
> +could be achieved. This is one of the thing I worked on during this hackathon:
```suggestion
could be achieved. This is one of the things I worked on during this hackathon: 
```

2019-04-09 05:54 UTC, OskarStark commented on achievements/flysystem.md
> +Gregoire Paris to write its documentation
Grégoire avec accent aigu? 🇫🇷

2019-04-09 06:26 UTC, greg0ire commented on achievements/flysystem.md
> +Gregoire Paris to write its documentation
Yes please :pray: 
```suggestion
Grégoire Paris to write its documentation 
```

2019-04-09 09:18 UTC, tgalopin commented
Updated!

2019-04-09 10:02 UTC, greg0ire approved these changes

2019-04-09 10:10 UTC, OskarStark approved these changes

2019-04-09 16:28 UTC, jfhovinne requested changes
Thanks! Minor fixes needed.

2019-04-09 16:28 UTC, jfhovinne commented on achievements/flysystem.md
> +# Flysystem / Symfony integration achievements
I would prefer a '-' instead of a '/'.

2019-04-09 16:28 UTC, jfhovinne commented on achievements/flysystem.md
> +However, this implementation had many problems and was not well suited to
'many issues' maybe (to avoid repeating the word) ?

2019-04-09 16:28 UTC, jfhovinne commented on achievements/flysystem.md
> +Symfony 4.2, in november 2018, and the hackathon was even the occasion for
November (N uppercase)

2019-04-09 16:28 UTC, jfhovinne commented on achievements/flysystem.md
> +It's not entierely finished but it will be in the coming days.
entirely

2019-04-09 20:55 UTC, tgalopin commented
Updated

2019-04-10 05:51 UTC, jfhovinne approved these changes

2019-04-10 05:51 UTC, merged

2019-04-10 05:51 UTC, jfhovinne commented
Thanks!