Add Box achievements
eufossa/symfony-hackathon-2019 pull request #24
Opened 2019-04-09 20:57 UTC by theofidry

2019-04-09 21:03 UTC, greg0ire requested changes

2019-04-09 21:03 UTC, greg0ire commented on achievements/box.md
> +[Humbug Box][box] is an application bunlder for PHP apps. It allows one to ship a PHP app into a PHAR and distribute it with
```suggestion
[Humbug Box][box] is an application bundler for PHP apps. It allows one to ship a PHP app into a PHAR and distribute it with 
```

2019-04-09 21:03 UTC, greg0ire commented on achievements/box.md
> +Thanks to this hackaton, [I][me] could besides working on other Symfony related issues, and with the help of
```suggestion
Thanks to this hackaton, [I][me] could, besides working on other Symfony related issues, and with the help of 
```

2019-04-09 21:03 UTC, greg0ire commented on achievements/box.md
> +- The realease of [Box 3.7.0][box-3.7.0]
```suggestion
- The release of [Box 3.7.0][box-3.7.0]
```

2019-04-09 21:03 UTC, greg0ire commented on achievements/box.md
> +[@nicolas-grekas][nicolas], [@stof][stof] and [@tucksaun][tucksaun], work on adding support for Symfony for Box.
```suggestion
[@nicolas-grekas][nicolas], [@stof][stof] and [@tucksaun][tucksaun], work on adding support for Symfony to Box.
```

2019-04-09 21:03 UTC, greg0ire commented on achievements/box.md
> +- Add additional screening on Symfony regarding the [HTTPoxy][httpoxy] vulnerability (not security issue found during the process)
```suggestion
- Adding additional screening on Symfony regarding the [HTTPoxy][httpoxy] vulnerability (no security issue found during the process)
```

2019-04-09 21:03 UTC, greg0ire commented on achievements/box.md
> +As well more discussions have been made on how to integrate a [REPL][repl] to Symfony with minimal dependencies (which has been
```suggestion
Also, more discussions have been made on how to integrate a [REPL][repl] to Symfony with minimal dependencies (which has been
```

2019-04-10 05:13 UTC, Simperfit approved these changes
after resolving @greg0ire comments :+1:

2019-04-10 06:57 UTC, greg0ire commented on achievements/box.md
> +Thanks to this hackaton, [I][me] could, besides working on other Symfony related issues, and with the help of
```suggestion
Thanks to this hackathon, [I][me] could, besides working on other Symfony related issues, and with the help of 
```

2019-04-10 07:00 UTC, greg0ire approved these changes

2019-04-10 07:54 UTC, Toflar commented on achievements/box.md
> +[repl]: https://es.wikipedia.org/wiki/REPL
```suggestion
[repl]: https://en.wikipedia.org/wiki/Read–eval–print_loop
```

2019-04-10 07:56 UTC, Toflar approved these changes

2019-04-10 08:03 UTC, stof commented on achievements/box.md
> +In contrast, while Box is being used with lot with projects making use of [Symfony][symfony] components, it cannot be used – at
typo. Should be `a lot`

2019-04-10 08:03 UTC, stof commented on achievements/box.md
> +[laravel]: http://laravel.com
should be HTTPS

2019-04-10 09:19 UTC, stof commented on achievements/box.md
> +In contrast, while Box is being used with a lot with projects making use of [Symfony][symfony] components, it cannot be used – at
The extra `with` should also be removed

2019-04-10 12:31 UTC, greg0ire commented on achievements/box.md
> +In contrast, while Box is being used a lot with projects making use of [Symfony][symfony] components, it cannot be used – at
You removed the wrong with ;)
```suggestion
In contrast, while Box is being used a lot with projects making use of [Symfony][symfony] components, it cannot be used – at
```

2019-04-10 16:53 UTC, jfhovinne requested changes

2019-04-10 16:53 UTC, jfhovinne commented on achievements/box.md
> +# Box Achievements
There is on ongoing discussion in #20 about capitalisation in titles. If we follow the EC style guide, only the first word takes a capital.

2019-04-10 16:53 UTC, jfhovinne commented on achievements/box.md
> +[@nicolas-grekas][nicolas], [@stof][stof] and [@tucksaun][tucksaun], work on adding support for Symfony to Box.
stof link does not display correctly (see rendered page), missing in the list below

2019-04-10 17:17 UTC, theofidry commented
@jfhovinne done

2019-04-10 18:49 UTC, jfhovinne approved these changes
Great, thanks! I see the link from homepage is missing, but will add it.

2019-04-10 18:49 UTC, merged