Add achievement secrets
eufossa/symfony-hackathon-2019 pull request #26
Opened 2019-04-10 16:01 UTC by jderusse

2019-04-10 16:10 UTC, OskarStark requested changes
Nice article 👍🏻

2019-04-10 16:10 UTC, OskarStark commented on achievements/secrets.md
> +The EU-FOSSA hackathon was the opportunity to discussed and define a simple
s/discussed/discuss/

2019-04-10 16:10 UTC, OskarStark commented on achievements/secrets.md
> +authentication keys, ...) in a symfony application.
s/symfony/Symfony/

2019-04-10 16:10 UTC, OskarStark commented on achievements/secrets.md
> +> How to define new sensitive parameter without exposing theme in a
s/theme/them/

2019-04-10 16:10 UTC, OskarStark commented on achievements/secrets.md
> +  Repository, nor configuring manually a server each time the projet requires
s/Repository/repository/

2019-04-10 16:10 UTC, OskarStark commented on achievements/secrets.md
> +  a new ENV variable
s/ENV/env/

2019-04-10 16:10 UTC, OskarStark commented on achievements/secrets.md
> +Thank to @mpdude, @tobion, @nicolas-grekas and @jderusse, we defined the
s/Thank/Thanks/

2019-04-10 16:10 UTC, OskarStark commented on achievements/secrets.md
> +use-cases that would be covered by that new feature, we desin the main
s/desin/design/

2019-04-10 19:03 UTC, jfhovinne requested changes
Thanks! Minor fixes.

2019-04-10 19:03 UTC, jfhovinne commented on achievements/secrets.md
> +Thanks to @mpdude, @tobion, @nicolas-grekas and @jderusse, we defined the
Could you link to the accounts ?

2019-04-10 19:03 UTC, jfhovinne commented on achievements/secrets.md
> +use-cases that would be covered by that new feature, we design the main
'use cases' and 'designed'

2019-04-10 19:03 UTC, jfhovinne commented on achievements/secrets.md
> +[Click here for the RFC issue](https://github.com/symfony/symfony/issues/27351).
Please avoid 'Click here' - https://www.w3.org/QA/Tips/noClickHere

2019-04-10 19:03 UTC, jfhovinne commented on achievements/secrets.md
> +  a new e,v variable
e,v

2019-04-11 08:13 UTC, jderusse commented on achievements/secrets.md
> +This subject was in initialized in [the RFC issue](https://github.com/symfony/symfony/issues/27351).
Shall we add a link to https://www.webfactory.de/blog/storing-secrets-for-symfony-applications ? ping @mpdude

2019-04-11 09:59 UTC, mpdude commented on achievements/secrets.md
> +This subject was in initialized in [the RFC issue](https://github.com/symfony/symfony/issues/27351).
Yes sure, why not?

2019-04-11 10:47 UTC, jderusse commented on achievements/secrets.md
> +This subject was in initialized in [the RFC issue](https://github.com/symfony/symfony/issues/27351).
Added.

> why not?

politely asking it :-)

2019-04-11 10:48 UTC, jderusse commented on achievements/secrets.md
> +Thanks to @mpdude, @tobion, @nicolas-grekas and @jderusse, we defined the
done. Thanks for the review

2019-04-11 17:00 UTC, jfhovinne requested changes
Typos.

2019-04-11 17:00 UTC, jfhovinne commented on achievements/secrets.md
> +This subject was in initialized in [the RFC issue](https://github.com/symfony/symfony/issues/27351),
"was initialised"

2019-04-11 17:00 UTC, jfhovinne commented on achievements/secrets.md
> +diging into that topic.
digging

2019-04-23 05:51 UTC, merged

2019-04-23 05:51 UTC, jfhovinne commented
Thanks. Will fix typos.